name = "KrigingModel"
uuid = "49b3b870-118c-11ea-1661-71d34d312539"
authors = ["XUE Cheng <xuecheng@nuaa.edu.cn>"]
version = "0.1.2"

[deps]
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GaussianProcesses = "891a1506-143c-57d2-908e-e1f8e92e6de9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DiffResults = "1.0"
ElasticArrays = "1.0"
ForwardDiff = "0.10"
GaussianProcesses = "0.11"
NLopt = "0.5, 0.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
